name: Auto Start VPS on Push

on:
  push:
    branches: [main]
    paths-ignore:
      - 'restart.lock'
      - '.backup/**'
      - 'links/**'

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Trigger VPS Creation
        run: |
          curl -X POST https://api.github.com/repos/uy38355e8355/vps-project-1757216369535/dispatches \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
          -d '{"event_type": "create-vps", "client_payload": {"vps_name": "autovps", "backup": false}}'
